name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [ .github/* ]
  pull_request: 
    branches: [ main ]
  # schedule:
  #   - cron: '15 6 * * SUN'
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-lastest
    steps:
      - run: |
          echo 'The event that triggered this workflow was ${{ github.event_name }}'
          echo 'The branch this workflow is running against is ${{ github.ref }}'
      - uses: actions/checkout@v4
      - run: tree
